export const LOGIN_RESET = "LOGIN_RESET";
export const ADD_TO_LOCALSTORAGE_REQUEST = "ADD_TO_LOCALSTORAGE_REQUEST";
export const ADD_TO_LOCALSTORAGE_SUCCESS = "ADD_TO_LOCALSTORAGE_SUCCESS";
export const ADD_TO_LOCALSTORAGE_FAIL = "ADD_TO_LOCALSTORAGE_FAIL";
export const ADD_TO_LOCALSTORAGE_RESET = "ADD_TO_LOCALSTORAGE_RESET";

export const VIEW_LOCALSTORAGE_REQUEST = "VIEW_LOCALSTORAGE_REQUEST";
export const VIEW_LOCALSTORAGE_SUCCESS = "VIEW_LOCALSTORAGE_SUCCESS";
export const VIEW_LOCALSTORAGE_FAIL = "VIEW_LOCALSTORAGE_FAIL";
export const VIEW_LOCALSTORAGE_RESET = "VIEW_LOCALSTORAGE_RESET";

export const UPDATE_LOCALSTORAGE_REQUEST = "UPDATE_LOCALSTORAGE_REQUEST";
export const UPDATE_LOCALSTORAGE_SUCCESS = "UPDATE_LOCALSTORAGE_SUCCESS";
export const UPDATE_LOCALSTORAGE_FAIL = "UPDATE_LOCALSTORAGE_FAIL";
export const UPDATE_LOCALSTORAGE_RESET = "UPDATE_LOCALSTORAGE_RESET";

export const REMOVE_FROM_LOCALSTORAGE_REQUEST =
  "REMOVE_FROM_LOCALSTORAGE_REQUEST";
export const REMOVE_FROM_LOCALSTORAGE_SUCCESS =
  "REMOVE_FROM_LOCALSTORAGE_SUCCESS";
export const REMOVE_FROM_LOCALSTORAGE_FAIL = "REMOVE_FROM_LOCALSTORAGE_FAIL";
export const REMOVE_FROM_LOCALSTORAGE_RESET = "REMOVE_FROM_LOCALSTORAGE_RESET";

export const GET_ALL_LOCAL_STORAGE_REQUEST = "GET_ALL_LOCAL_STORAGE_REQUEST";
export const GET_ALL_LOCAL_STORAGE_SUCCESS = "GET_ALL_LOCAL_STORAGE_SUCCESS";
export const GET_ALL_LOCAL_STORAGE_FAILURE = "GET_ALL_LOCAL_STORAGE_FAILURE";
